###
POST http://localhost:3306/users
Content-Type: application/json

{
    "name": "Heber",
    "email": "heber@gmail.com",
    "password": "heber83"
}

###

GET  http://localhost:3306/users

###
POST http://localhost:3306/products
Content-Type:  application/json

{
    "name": "Viagem para os EUA",
    "price": 5000,
    "image": "https://picsum.photos/seed/picsum/200/300"
}

###
GET  http://localhost:3306/products